### ISSUE TITLE
Cannot update seller back to the same authTokenId & authTokenType

### ISSUE THREAD

**Issue by albertfolch-redeemeum** [bosonprotocol/boson-protocol-contracts#623]
If you create a seller with an authTokenId X and authTokenType A, then you update it to authTokenId Y and authTokenType B and then back to authTokenId X and authTokenType A, you will get the error **_Auth token cannot be assigned to another entity of the same type_**. There seems to be a bug where the old authTokenId and/or authTokenType are not cleared.

**Comment by zajck** [comment]
This happens, since `optInToSellerUpdate` only deletes auth tokens info, but does not delete `lookups.sellerIdByAuthToken`, which is used to ensure uniqueness.

https://github.com/bosonprotocol/boson-protocol-contracts/blob/d65bed2210d577df5535d61aeb90437c0fe70648/contracts/protocol/facets/SellerHandlerFacet.sol#L240-L257

**PoC**
```
      it("Auth token can be used again if it was previously removed", async function () {
        // Create a seller with auth token
        seller.admin = ethers.constants.AddressZero;
        await accountHandler.connect(admin).createSeller(seller, authToken, voucherInitValues);

        // Update seller to not use auth token anymore
        seller.admin = other1.address;
        await accountHandler.connect(admin).updateSeller(seller, emptyAuthToken);
        await accountHandler.connect(other1).optInToSellerUpdate(seller.id, [SellerUpdateFields.Admin]);

        // Try to update back to auth token // it fails
        seller.admin = ethers.constants.AddressZero;
        await accountHandler.connect(other1).updateSeller(seller, authToken);
      });
```

**Recommendation**
Delete ``lookups.sellerIdByAuthToken` when admin is updated in `optInToSellerUpdate`
